import { Request, Response } from 'express';
import JSZip from 'jszip';

export const downloadTerraformProject = async (req: Request, res: Response) => {
  try {
    const { terraformCode, projectName, blueprint } = req.body;

    if (!terraformCode) {
      return res.status(400).json({ error: "No code provided to download." });
    }

    const zip = new JSZip();
    const rootFolder = zip.folder(projectName || "aws-infra-project");

    // 1. main.tf (The heavy lifting)
    rootFolder?.file("main.tf", 
      `# Generated by CloudArchitect AI\n# Project: ${projectName}\n\n${terraformCode}`
    );

    // 2. variables.tf (Standardized variables)
    rootFolder?.file("variables.tf", `
variable "region" {
  description = "AWS Region"
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Project Name"
  type        = string
  default     = "${projectName}"
}
    `);

    // 3. outputs.tf (Placeholders for after deployment)
    rootFolder?.file("outputs.tf", `
output "vpc_id" {
  value = "Check AWS Console after terraform apply"
}
    `);

    // 4. README.md (Professional instructions)
    rootFolder?.file("README.md", `
# ${projectName} Infrastructure
Generated by CloudArchitect Agentic AI.

## How to Deploy
1. Install Terraform CLI.
2. Run \`terraform init\` to download providers.
3. Run \`terraform plan\` to preview changes.
4. Run \`terraform apply\` to build your cloud!
    `);

    // Generate ZIP buffer
    const content = await zip.generateAsync({ type: "nodebuffer" });

    // Set headers for file download
    res.set({
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename=${projectName}.zip`,
      'Content-Length': content.length
    });

    return res.send(content);

  } catch (error) {
    console.error("Download Error:", error);
    return res.status(500).json({ error: "Failed to generate ZIP file." });
  }
};